package ru.bartwell.delightsqlviewer.adapter.sqldelight

import ru.bartwell.delightsqlviewer.AndroidEnvironmentProvider

public abstract class SqlDelightEnvironmentProvider : AndroidEnvironmentProvider
